name: Run Integration Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/fal-ai/fal
          pip install -e projects/fal
          pip install pytest pytest-asyncio pillow

      - name: Check secrets
        env:
            FAL_CLOUD_KEY_ID: ${{ secrets.FAL_CLOUD_KEY_ID }}
            FAL_CLOUD_KEY_SECRET: ${{ secrets.FAL_CLOUD_KEY_SECRET }}
            FAL_CLOUD_INTEGRATION_TEST_HOST: ${{ vars.FAL_CLOUD_INTEGRATION_TEST_HOST }}
        if: ${{ env.FAL_CLOUD_KEY_ID == '' || env.FAL_CLOUD_KEY_SECRET == '' || FAL_CLOUD_INTEGRATION_TEST_HOST == ''}}
        uses: actions/github-script@v3
        with:
            script: |
                core.setFailed('Missing secrets')

      - name: Run integration tests
        env:
          FAL_KEY: ${{ secrets.FAL_CLOUD_KEY_ID }}:${{ secrets.FAL_CLOUD_KEY_SECRET }}
          FAL_HOST: api.${{ vars.FAL_CLOUD_INTEGRATION_TEST_HOST }}
        run: |
          pytest -v projects/fal/tests
